Vdg/product picture
WildCodeSchool/2023-09-wns-rouge-renthub-back pull request #56
Opened 2024-05-17 21:04 UTC by victorDGW

fix : add picture info on resolver GetproductReference

2024-05-18 05:53 UTC, hugodavid1 requested changes

2024-05-18 05:53 UTC, hugodavid1 commented on src/resolvers/ProductReference.resolver.ts
> +      console.log('--------------------', productRef?.pictureProduct)
Console log

2024-05-18 08:33 UTC, victorDGW commented on src/resolvers/ProductReference.resolver.ts
> +      console.log('--------------------', productRef?.pictureProduct)
Très juste , Il Faut configurer le prettier pour ne pas laisser passer les console.log. j en ai supprimer deux déjà mais celui ci je ne l avais pas vu...

2024-06-11 06:53 UTC, Megakrash approved these changes

2024-06-12 09:18 UTC, merged